#!/usr/bin/env node
// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * @file Build pipeline: eval → Vite build → inject data into HTML
 *
 * Builds the report app, then injects evaluation data directly into
 * the HTML as a <script> tag. This guarantees the data is available
 * before React renders — no module import race conditions.
 *
 * Usage:
 *   tsx src/build-report.ts --iteration <id>
 *   tsx src/build-report.ts --iteration <id> --baseline <id>
 *   tsx src/build-report.ts --iteration <id> --baseline <id> --with-screenshots
 *   tsx src/build-report.ts --iteration <id> --dev
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {execSync} from 'node:child_process';
import {getResultsDir, readJson, ensureDir, ensureCodeFiles} from './utils.js';
import type {
  TargetName,
  UniversalAggregate,
  UniversalComparison,
} from './types.js';
import {getTargetResultExtension} from './target-config.js';

const APP_DIR = path.join(import.meta.dirname, '..', 'app');
const REPO_ROOT = path.join(import.meta.dirname, '../../..');

/**
 * Ensure pre-compiled CSS dist files exist.
 *
 * The report build uses pre-compiled CSS from:
 * - packages/core/dist/astryx.css (component styles)
 * - packages/themes/neutral/dist/theme.css (theme tokens)
 *
 * These are generated by `pnpm build` but may not exist if the repo
 * was freshly cloned or only `pnpm install` was run.
 */
function ensureCssDist(): void {
  const astryxCss = path.join(REPO_ROOT, 'packages/core/dist/astryx.css');
  const themeCss = path.join(
    REPO_ROOT,
    'packages/themes/neutral/dist/theme.css',
  );

  const missing: string[] = [];
  if (!fs.existsSync(astryxCss)) {
    missing.push('@astryxdesign/core/dist/astryx.css');
  }
  if (!fs.existsSync(themeCss)) {
    missing.push('@astryxdesign/theme-neutral/dist/theme.css');
  }

  if (missing.length > 0) {
    console.log('📦 Building CSS dist files (required for report)...');
    console.log(`   Missing: ${missing.join(', ')}`);

    // Build core package (includes astryx.css via postbuild)
    if (!fs.existsSync(astryxCss)) {
      execSync('pnpm -F @astryxdesign/core build', {
        cwd: REPO_ROOT,
        stdio: 'inherit',
      });
    }

    // Build theme packages
    if (!fs.existsSync(themeCss)) {
      execSync('pnpm -F @astryxdesign/theme-neutral build', {
        cwd: REPO_ROOT,
        stdio: 'inherit',
      });
    }

    console.log('   ✓ CSS dist files ready\n');
  }
}

function parseArgs(): {
  iteration: string;
  baseline?: string;
  html?: string;
  astryxTailwind?: string;
  astryxSvelte?: string;
  withScreenshots: boolean;
  dev: boolean;
} {
  const args = process.argv.slice(2);
  let iteration = '';
  let baseline: string | undefined;
  let html: string | undefined;
  let astryxTailwind: string | undefined;
  let astryxSvelte: string | undefined;
  let withScreenshots = false;
  let dev = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--iteration' && args[i + 1]) {
      iteration = args[i + 1];
      i++;
    } else if (args[i] === '--baseline' && args[i + 1]) {
      baseline = args[i + 1];
      i++;
    } else if (args[i] === '--html' && args[i + 1]) {
      html = args[i + 1];
      i++;
    } else if (args[i] === '--astryx-tailwind' && args[i + 1]) {
      astryxTailwind = args[i + 1];
      i++;
    } else if (args[i] === '--astryx-svelte' && args[i + 1]) {
      astryxSvelte = args[i + 1];
      i++;
    } else if (args[i] === '--with-screenshots') {
      withScreenshots = true;
    } else if (args[i] === '--dev') {
      dev = true;
    }
  }

  if (!iteration) {
    console.error(
      'Usage: tsx src/build-report.ts --iteration <id> [--baseline <id>] [--html <id>] [--astryx-tailwind <id>] [--astryx-svelte <id>] [--with-screenshots] [--dev]',
    );
    process.exit(1);
  }

  return {
    iteration,
    baseline,
    html,
    astryxTailwind,
    astryxSvelte,
    withScreenshots,
    dev,
  };
}

function ensureUniversalJson(iteration: string): UniversalAggregate {
  const resultsDir = getResultsDir();
  const universalPath = path.join(resultsDir, iteration, 'universal.json');

  if (!fs.existsSync(universalPath)) {
    console.log(`Generating universal.json for ${iteration}...`);
    execSync(
      `tsx ${path.join(import.meta.dirname, 'universal-aggregate.ts')} --iteration ${iteration}`,
      {cwd: path.join(import.meta.dirname, '..'), stdio: 'inherit'},
    );
  }

  return readJson<UniversalAggregate>(universalPath);
}

function ensureComparison(
  xdsId: string,
  baselineId: string,
  htmlId?: string,
  astryxTailwindId?: string,
  astryxSvelteId?: string,
): UniversalComparison {
  const resultsDir = getResultsDir();
  const idParts = [xdsId, baselineId];
  if (htmlId) {
    idParts.push(htmlId);
  }
  if (astryxTailwindId) {
    idParts.push(astryxTailwindId);
  }
  if (astryxSvelteId) {
    idParts.push(astryxSvelteId);
  }
  const comparisonFilename = `comparison-${idParts.join('-')}.json`;
  const comparisonPath = path.join(resultsDir, comparisonFilename);

  if (!fs.existsSync(comparisonPath)) {
    const htmlFlag = htmlId ? ` --html ${htmlId}` : '';
    const twFlag = astryxTailwindId
      ? ` --astryx-tailwind ${astryxTailwindId}`
      : '';
    const svelteFlag = astryxSvelteId
      ? ` --astryx-svelte ${astryxSvelteId}`
      : '';
    const vsLabel = [baselineId, htmlId, astryxTailwindId, astryxSvelteId]
      .filter(Boolean)
      .join(' vs ');
    console.log(`Generating comparison for ${xdsId} vs ${vsLabel}...`);
    execSync(
      `tsx ${path.join(import.meta.dirname, 'universal-compare.ts')} --astryx ${xdsId} --baseline ${baselineId}${htmlFlag}${twFlag}${svelteFlag}`,
      {cwd: path.join(import.meta.dirname, '..'), stdio: 'inherit'},
    );
  }

  return readJson<UniversalComparison>(comparisonPath);
}

/**
 * Extract prompt text from the manifest's prompts array.
 * Returns a map of promptId → prompt text.
 */
function extractPrompts(manifest: unknown): Record<string, string> {
  const prompts: Record<string, string> = {};
  const m = manifest as {prompts?: Array<{id: string; prompt: string}>};
  if (m.prompts && Array.isArray(m.prompts)) {
    for (const p of m.prompts) {
      if (p.id && p.prompt) {
        prompts[p.id] = p.prompt;
      }
    }
  }
  return prompts;
}

function loadSourceCodeForIteration(iteration: string): Record<string, string> {
  const resultsDir = getResultsDir();
  const iterDir = path.join(resultsDir, iteration);
  const manifestPath = path.join(iterDir, 'manifest.json');
  const manifest = readJson<{config?: {target?: TargetName}}>(manifestPath);
  const target = manifest.config?.target ?? 'astryx';
  const extension = getTargetResultExtension(target);
  const codeDir = path.join(iterDir, 'results');
  const sourceCode: Record<string, string> = {};

  if (!fs.existsSync(codeDir)) {
    return sourceCode;
  }

  ensureCodeFiles(codeDir, extension);
  for (const file of fs
    .readdirSync(codeDir)
    .filter(f => f.endsWith(extension))) {
    const promptId = path.basename(file, extension);
    sourceCode[promptId] = fs.readFileSync(path.join(codeDir, file), 'utf-8');
  }

  return sourceCode;
}

/**
 * Build the report data as a <script> tag to inject into the HTML.
 * This runs before the app bundle, so window.__REPORT_DATA__ is
 * guaranteed to exist when React renders.
 */
function buildDataScript(opts: {
  iteration: string;
  iterationData: UniversalAggregate;
  baseline?: string;
  comparison?: UniversalComparison;
  manifest: unknown;
  sourceCode?: Record<string, string>;
  baselineSourceCode?: Record<string, string>;
  htmlSourceCode?: Record<string, string>;
  astryxTailwindSourceCode?: Record<string, string>;
  astryxSvelteSourceCode?: Record<string, string>;
  previews?: Record<string, Record<string, string>>;
  screenshots?: Record<string, string>;
  prompts?: Record<string, string>;
}): string {
  const reportData = {
    universal: opts.iterationData,
    comparison: opts.comparison ?? undefined,
    iterationId: opts.iteration,
    target: (opts.manifest as {config?: {target?: string}})?.config?.target,
    sourceCode: opts.sourceCode,
    baselineSourceCode: opts.baselineSourceCode,
    htmlSourceCode: opts.htmlSourceCode,
    astryxTailwindSourceCode: opts.astryxTailwindSourceCode,
    astryxSvelteSourceCode: opts.astryxSvelteSourceCode,
    previews: opts.previews,
    screenshots: opts.screenshots,
    prompts: opts.prompts,
  };

  return `<script>window.__REPORT_DATA__=${JSON.stringify(reportData)};</script>`;
}

/**
 * Inject the data script into the built HTML, before the first <script> tag
 * so it runs before the app bundle.
 */
function injectDataIntoHtml(htmlPath: string, dataScript: string): void {
  let html = fs.readFileSync(htmlPath, 'utf-8');
  const firstScript = html.indexOf('<script');
  if (firstScript === -1) {
    html = html.replace('</body>', `${dataScript}\n</body>`);
  } else {
    html =
      html.slice(0, firstScript) + dataScript + '\n' + html.slice(firstScript);
  }
  fs.writeFileSync(htmlPath, html);
}

/**
 * Inline any CSS files from dist/assets/ that vite-plugin-singlefile
 * didn't handle (e.g. StyleX extracted CSS).
 */
function inlineCss(htmlPath: string, distDir: string): void {
  const assetsDir = path.join(distDir, 'assets');
  if (!fs.existsSync(assetsDir)) {
    return;
  }

  const cssFiles = fs.readdirSync(assetsDir).filter(f => f.endsWith('.css'));
  if (cssFiles.length === 0) {
    return;
  }

  console.log(`   Inlining ${cssFiles.length} CSS file(s)...`);
  let html = fs.readFileSync(htmlPath, 'utf-8');
  for (const cssFile of cssFiles) {
    const css = fs.readFileSync(path.join(assetsDir, cssFile), 'utf-8');
    html = html.replace('</head>', `<style>${css}</style>\n</head>`);
  }
  fs.writeFileSync(htmlPath, html);
}

async function main() {
  const {
    iteration,
    baseline,
    html,
    astryxTailwind,
    astryxSvelte,
    withScreenshots: _withScreenshots,
    dev,
  } = parseArgs();
  const resultsDir = getResultsDir();
  const iterDir = path.join(resultsDir, iteration);
  const manifestPath = path.join(iterDir, 'manifest.json');

  if (!fs.existsSync(manifestPath)) {
    console.error(`No manifest.json found at ${manifestPath}`);
    process.exit(1);
  }

  const manifest = readJson(manifestPath);

  // Step 1: Ensure universal.json exists
  console.log('📊 Step 1: Ensuring evaluation data...');
  const iterationData = ensureUniversalJson(iteration);

  // Step 2: If baseline provided, ensure comparison
  let comparison: UniversalComparison | undefined;
  if (baseline) {
    console.log('📊 Step 2: Ensuring comparison data...');
    ensureUniversalJson(baseline);
    if (html) {
      ensureUniversalJson(html);
    }
    if (astryxTailwind) {
      ensureUniversalJson(astryxTailwind);
    }
    if (astryxSvelte) {
      ensureUniversalJson(astryxSvelte);
    }
    comparison = ensureComparison(
      iteration,
      baseline,
      html,
      astryxTailwind,
      astryxSvelte,
    );
  }

  // Step 3: Load source code for per-prompt inspection
  console.log('📝 Step 3: Preparing report data...');
  const sourceCode = loadSourceCodeForIteration(iteration);

  let baselineSourceCode: Record<string, string> | undefined;
  if (baseline) {
    baselineSourceCode = loadSourceCodeForIteration(baseline);
  }

  let htmlSourceCode: Record<string, string> | undefined;
  if (html) {
    htmlSourceCode = loadSourceCodeForIteration(html);
  }

  let astryxTailwindSourceCode: Record<string, string> | undefined;
  if (astryxTailwind) {
    astryxTailwindSourceCode = loadSourceCodeForIteration(astryxTailwind);
  }

  let astryxSvelteSourceCode: Record<string, string> | undefined;
  if (astryxSvelte) {
    astryxSvelteSourceCode = loadSourceCodeForIteration(astryxSvelte);
  }

  // Load preview manifest if available
  const previewManifestPath = path.join(iterDir, 'previews', 'manifest.json');
  let previews: Record<string, Record<string, string>> | undefined;
  if (fs.existsSync(previewManifestPath)) {
    const parsed: Record<string, Record<string, string>> = JSON.parse(
      fs.readFileSync(previewManifestPath, 'utf-8'),
    );
    previews = parsed;
    console.log(
      `  ✓ Preview manifest loaded (${Object.keys(parsed).length} prompts)`,
    );
  }

  // Load screenshot manifests from all iterations
  // Screenshots use relative paths (screenshots/filename.png) that resolve
  // when deployed to gh-pages alongside the report.
  let screenshots: Record<string, string> | undefined;
  for (const id of [
    iteration,
    baseline,
    html,
    astryxTailwind,
    astryxSvelte,
  ].filter(Boolean) as string[]) {
    const screenshotManifestPath = path.join(
      resultsDir,
      id,
      'screenshots',
      'manifest.json',
    );
    if (fs.existsSync(screenshotManifestPath)) {
      const manifest = JSON.parse(
        fs.readFileSync(screenshotManifestPath, 'utf-8'),
      );
      if (!screenshots) {
        screenshots = {};
      }
      // Flatten the nested manifest into filename → relative URL
      for (const [_promptId, targets] of Object.entries(manifest)) {
        for (const [_target, viewports] of Object.entries(
          targets as Record<string, Record<string, Record<string, string>>>,
        )) {
          for (const [_viewport, themes] of Object.entries(
            viewports as Record<string, Record<string, string>>,
          )) {
            for (const [_theme, filename] of Object.entries(
              themes as Record<string, string>,
            )) {
              screenshots[filename] = `screenshots/${filename}`;
            }
          }
        }
      }
    }
  }
  if (screenshots) {
    console.log(
      `  ✓ Screenshot manifest loaded (${Object.keys(screenshots).length} images)`,
    );
  }

  // Extract prompt text from manifest
  const prompts = extractPrompts(manifest);
  if (Object.keys(prompts).length > 0) {
    console.log(
      `  ✓ Prompt text loaded (${Object.keys(prompts).length} prompts)`,
    );
  }

  // Step 4: Build the data script
  const dataScript = buildDataScript({
    iteration,
    iterationData,
    baseline,
    comparison,
    manifest,
    sourceCode,
    baselineSourceCode,
    htmlSourceCode,
    astryxTailwindSourceCode,
    astryxSvelteSourceCode,
    previews,
    screenshots,
    prompts,
  });
  console.log(`  ✓ ${(dataScript.length / 1024).toFixed(0)} KB of report data`);

  // Step 5: Ensure CSS dist files exist (needed for report build)
  ensureCssDist();

  // Step 6: Dev mode or build
  if (dev) {
    // For dev mode, write data to a module file so Vite can serve it
    const dataDir = path.join(APP_DIR, 'src', 'data');
    ensureDir(dataDir);
    const reportData = {
      universal: iterationData,
      comparison: comparison ?? undefined,
      iterationId: iteration,
      target: (manifest as {config?: {target?: string}})?.config?.target,
      sourceCode,
      baselineSourceCode,
      htmlSourceCode,
      astryxTailwindSourceCode,
      astryxSvelteSourceCode,
      previews,
      screenshots,
      prompts,
    };
    fs.writeFileSync(
      path.join(dataDir, 'report-data.ts'),
      `// AUTO-GENERATED for dev mode\nObject.assign(window, {__REPORT_DATA__: ${JSON.stringify(reportData, null, 2)}});\n`,
    );

    console.log('\n🚀 Starting Vite dev server...');
    const {createServer} = await import('vite');
    const server = await createServer({
      root: APP_DIR,
      configFile: path.join(APP_DIR, 'vite.config.report.ts'),
      server: {port: 5173, strictPort: true},
    });
    await server.listen();
    server.printUrls();
    console.log('\nOpen http://localhost:5173 to view the report.');
    console.log('Press Ctrl+C to stop.\n');
  } else {
    console.log('\n🏗️  Step 5: Building static report...');
    execSync('npx vite build --config vite.config.report.ts', {
      cwd: APP_DIR,
      stdio: 'inherit',
    });

    // Step 5: Inject data and styles into the built HTML
    const distDir = path.join(APP_DIR, 'dist');
    const reportHtml = path.join(distDir, 'index.report.html');
    if (fs.existsSync(reportHtml)) {
      console.log('💉 Step 6: Injecting report data and styles...');
      injectDataIntoHtml(reportHtml, dataScript);
      inlineCss(reportHtml, distDir);

      const destPath = path.join(iterDir, 'report.html');
      fs.copyFileSync(reportHtml, destPath);
      console.log(`\n✅ Report saved to: ${destPath}`);
    } else {
      console.error('Build succeeded but no index.report.html found in dist/');
    }
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
